Added 6 temp views, added navigation logic
schiedel-sweden/Mobile-Application pull request #18
Opened 2017-10-02 16:18 UTC by JonathanPartain

2017-10-02 18:32 UTC, jeremydanner requested changes

2017-10-02 18:32 UTC, jeremydanner commented on src/views/PriceSuggestion/Bestallning.js
> +export default class Bestallning extends Component {
Fix class Name?

2017-10-02 18:32 UTC, jeremydanner commented on src/views/PriceSuggestion/Hustyp.js
> +export default class Hustyp extends Component {
Fix class name to English

2017-10-02 18:32 UTC, jeremydanner commented on src/views/PriceSuggestion/Kundupgifter.js
> +export default class Kundupgifter extends Component {
Class name

2017-10-02 18:35 UTC, jeremydanner requested changes

2017-10-02 18:35 UTC, jeremydanner commented on src/views/PriceSuggestion/PriceSuggestion.js
> +    skorstenstyp(){
Change the method names to English!

2017-10-02 19:35 UTC, JonathanPartain commented
@jeremydanner Please make sure everything looks as it should, then merge!

2017-10-03 05:30 UTC, jeremydanner approved these changes
Topp! Jag mergar.

2017-10-03 05:31 UTC, merged