Price suggestion pages
schiedel-sweden/Mobile-Application pull request #45
Opened 2017-10-31 17:18 UTC by JonathanPartain

First two pages, chimneytype and housetype to save state so information does not dissapear when navigating

2017-11-01 08:03 UTC, jeremydanner requested changes

2017-11-01 08:03 UTC, jeremydanner commented on src/components/NumberInput/IncNumberInput.js
> +        if (text != '') {
JavaScript är inte typat! `!==`

2017-11-01 08:03 UTC, jeremydanner commented on src/views/PriceSuggestion/Chimney.js
> +            console.log(error);
Ta bort `console.log` och retunera ett error till användaren om det anses vara behövligt!

2017-11-01 08:03 UTC, jeremydanner commented on src/views/PriceSuggestion/ChimneyType.js
>          if (i == 0) {
Samma här! `===`

2017-11-01 08:03 UTC, jeremydanner commented on src/views/PriceSuggestion/HouseType.js
>                          pretext={'Total Höjd (H1)'}
Propsen borde kunna skrivas `pretext="Höjd över tak (H2)"` istället för att kalla på en sträng på de sättet

2017-11-01 09:51 UTC, JonathanPartain commented on src/views/PriceSuggestion/Chimney.js
> +            console.log(error);
Det borde aldrig bli en error, så det är mest för utvecklingskäl

2017-11-01 09:53 UTC, JonathanPartain commented
@jeremydanner Tror jag fick med alla förändringar som skulle med, men kolla gärna igenom en gång till! :smile:

2017-11-01 17:16 UTC, jeremydanner requested changes
Antar att det ska vara = och inte 0? du kan merga när det är fixat!

2017-11-01 17:16 UTC, jeremydanner commented on src/views/PriceSuggestion/ChimneyType.js
> +        if (i ==0 1) {
0?

2017-11-06 13:33 UTC, JonathanPartain commented on src/views/PriceSuggestion/ChimneyType.js
> +        if (i ==0 1) {
Typo, korrekt

2017-11-06 13:33 UTC, merged